In [2]:
# 1. Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# 2. Load dataset
X, y = load_iris(return_X_y=True)

# 3. Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 4. Scale features
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 5. Create ANN with 1 hidden layer of 8 neurons using logistic activation
clf = MLPClassifier(hidden_layer_sizes=(8,), activation='logistic', solver='lbfgs', random_state=42)

# 6. Train the ANN
clf.fit(X_train, y_train)

# 7. Predict on test set
y_pred = clf.predict(X_test)

# 8. Print training accuracy
print("Train Accuracy:", accuracy_score(y_train, clf.predict(X_train)))

# 9. Print test accuracy
print("Test Accuracy:", accuracy_score(y_test, y_pred))

# 10. Print confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Train Accuracy: 1.0
Test Accuracy: 0.9736842105263158

Confusion Matrix:
 [[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]


In [7]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Load and preprocess the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# One-hot encode the target labels
encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y)

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

# Activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Initialize network parameters
input_size = X_train.shape[1]
hidden_size = 10
output_size = y_train.shape[1]
learning_rate = 0.1
epochs = 1000

# Weights and biases
np.random.seed(42)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_hidden = np.zeros((1, hidden_size))
bias_output = np.zeros((1, output_size))

# Training loop
for epoch in range(epochs):
    # Forward pass
    hidden_input = np.dot(X_train, weights_input_hidden) + bias_hidden
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    final_output = sigmoid(final_input)

    # Backpropagation
    error = y_train - final_output
    d_output = error * sigmoid_derivative(final_output)

    error_hidden = d_output.dot(weights_hidden_output.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate
    bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    weights_input_hidden += X_train.T.dot(d_hidden) * learning_rate
    bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    if epoch % 100 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Testing
hidden_input = np.dot(X_test, weights_input_hidden) + bias_hidden
hidden_output = sigmoid(hidden_input)
final_input = np.dot(hidden_output, weights_hidden_output) + bias_output
final_output = sigmoid(final_input)

# Accuracy
predictions = np.argmax(final_output, axis=1)
actual = np.argmax(y_test, axis=1)
accuracy = np.mean(predictions == actual)
print(f"\nTest Accuracy: {accuracy * 100:.2f}%")


Epoch 0, Loss: 0.5221
Epoch 100, Loss: 0.0148
Epoch 200, Loss: 0.0117
Epoch 300, Loss: 0.0109
Epoch 400, Loss: 0.0106
Epoch 500, Loss: 0.0104
Epoch 600, Loss: 0.0103
Epoch 700, Loss: 0.0102
Epoch 800, Loss: 0.0102
Epoch 900, Loss: 0.0101

Test Accuracy: 100.00%
